{
  "type": "issue",
  "issue": {
    "id": 2203983562,
    "node_id": "I_kwDOABII586DXh7K",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29711",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29711/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29711/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29711/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/29711",
    "number": 29711,
    "state": "open",
    "state_reason": null,
    "title": "Wallet: Nondescript error message for 502nd unconfirmed transaction",
    "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing issues\n\n### Current behaviour\n\nWhen creating a large number of unconfirmed transactions (e.g. 500+) with `bitcoin-cli` by spending/sending from a wallet, sending/spending the 502nd time results in a nondescript error message.  It may be the case that this is expected behavior (e.g. reaching a limit), and the error message could be made more descriptive/informative. \r\n\r\n```\r\nerror code: -1\r\nerror message:\r\nmap::at\r\n```\r\n\r\nThis was encountered when creating a test to populate the mempool with a high number of transactions for the v27.0 RC Testing Guide.  This behavior was observed both on v26.0 and v27.0 rc1.\r\n\r\nConfirming the transactions in a block allows the user to perform additional spending.\n\n### Expected behaviour\n\nA more descriptive error message would be provided to the user.  In this case, if a limit is being reached, the user could be informed and take appropriate action (e.g. wait until a block confirms transactions, etc.).\n\n### Steps to reproduce\n\nStart a node on regtest with its own datadir/bitcoin.conf:\r\n```bash\r\nexport DATA_DIR=/tmp/tmpdatadir\r\nmkdir $DATA_DIR\r\nexport BINARY_PATH=/path/to/dir/containing/bitcoind\r\nalias bitcoind-test=\"$BINARY_PATH/bitcoind -datadir=$DATA_DIR\"\r\nalias bcli=\"$BINARY_PATH/bitcoin-cli -datadir=$DATA_DIR\"\r\necho \"regtest=1\" > $DATA_DIR/bitcoin.conf\r\nbitcoind-test -daemon\r\n```\r\nCreate a wallet, fund it with coinbase outputs, and send 501 times:\r\n```bash\r\nbcli createwallet test\r\nexport ADDRESS=$(bcli -rpcwallet=test getnewaddress)\r\nbcli -rpcwallet=test -generate 701\r\nfor i in $(seq 1 499); do bcli -rpcwallet=test -named send outputs=\"{\\\"$ADDRESS\\\": 1}\" fee_rate=10; done\r\nbcli -rpcwallet=test getmempoolinfo\r\nbcli -rpcwallet=test -named send outputs=\"{\\\"$ADDRESS\\\": 1}\" fee_rate=10\r\nbcli -rpcwallet=test getmempoolinfo\r\nbcli -rpcwallet=test -named send outputs=\"{\\\"$ADDRESS\\\": 1}\" fee_rate=10\r\nbcli -rpcwallet=test getmempoolinfo\r\n```\r\nInduce the error on the 502nd send:\r\n```bash\r\nbcli -rpcwallet=test -named send outputs=\"{\\\"$ADDRESS\\\": 1}\" fee_rate=10\r\nerror code: -1\r\nerror message:\r\nmap::at\r\n```\r\nConfirm transactions, then add a new transaction:\r\n```bash\r\nbcli -rpcwallet=test -generate 1\r\nbcli -rpcwallet=test -named send outputs=\"{\\\"$ADDRESS\\\": 1}\" fee_rate=10\r\nbcli -rpcwallet=test getmempoolinfo\r\n```\n\n### Relevant log output\n\nNothing relevant observed in debug.log at the time of the error received.\n\n### How did you obtain Bitcoin Core\n\nPre-built binaries\n\n### What version of Bitcoin Core are you using?\n\nv26.0.0\n\n### Operating system and version\n\nUbuntu 22.04 LTS\n\n### Machine specifications\n\namd64",
    "user": {
      "login": "tdb3",
      "id": 106488469,
      "node_id": "U_kgDOBljilQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/106488469?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tdb3",
      "html_url": "https://github.com/tdb3",
      "followers_url": "https://api.github.com/users/tdb3/followers",
      "following_url": "https://api.github.com/users/tdb3/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/tdb3/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/tdb3/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/tdb3/subscriptions",
      "organizations_url": "https://api.github.com/users/tdb3/orgs",
      "repos_url": "https://api.github.com/users/tdb3/repos",
      "events_url": "https://api.github.com/users/tdb3/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/tdb3/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [],
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "locked": false,
    "comments": 1,
    "created_at": "2024-03-23T17:58:53Z",
    "updated_at": "2024-03-23T18:28:52Z"
  },
  "events": [
    {
      "event": "commented",
      "id": 2016567004,
      "node_id": "IC_kwDOABII5854Ml7c",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2016567004",
      "actor": {
        "login": "achow101",
        "id": 3782274,
        "node_id": "MDQ6VXNlcjM3ODIyNzQ=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3782274?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/achow101",
        "html_url": "https://github.com/achow101",
        "followers_url": "https://api.github.com/users/achow101/followers",
        "following_url": "https://api.github.com/users/achow101/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/achow101/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/achow101/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/achow101/subscriptions",
        "organizations_url": "https://api.github.com/users/achow101/orgs",
        "repos_url": "https://api.github.com/users/achow101/repos",
        "events_url": "https://api.github.com/users/achow101/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/achow101/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-03-23T18:19:16Z",
      "updated_at": "2024-03-23T18:19:42Z",
      "author_association": "MEMBER",
      "body": "It's hitting the 500 tx cluster limit in MiniMiner, which I think we should keep. The error message just needs to be better. The error is happening when the result of `CalculateIndividualBumpFees` is an empty map, but we try to get things from it, so the fix would be to return a proper error when that map is empty.",
      "user": {
        "login": "achow101",
        "id": 3782274,
        "node_id": "MDQ6VXNlcjM3ODIyNzQ=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3782274?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/achow101",
        "html_url": "https://github.com/achow101",
        "followers_url": "https://api.github.com/users/achow101/followers",
        "following_url": "https://api.github.com/users/achow101/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/achow101/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/achow101/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/achow101/subscriptions",
        "organizations_url": "https://api.github.com/users/achow101/orgs",
        "repos_url": "https://api.github.com/users/achow101/repos",
        "events_url": "https://api.github.com/users/achow101/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/achow101/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/29711#issuecomment-2016567004",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29711"
    }
  ]
}