{
  "type": "issue",
  "issue": {
    "id": 2390290074,
    "node_id": "I_kwDOABII586OeO6a",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/30390",
    "number": 30390,
    "state": "open",
    "state_reason": null,
    "title": "ci: ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it",
    "body": "Usually they come with a follow-up error of `Unable to connect to bitcoind after 2400s` (or similar).\r\n\r\nThis is a tracking issue, because all tests are affected.",
    "user": {
      "login": "maflcko",
      "id": 6399679,
      "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/maflcko",
      "html_url": "https://github.com/maflcko",
      "followers_url": "https://api.github.com/users/maflcko/followers",
      "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
      "organizations_url": "https://api.github.com/users/maflcko/orgs",
      "repos_url": "https://api.github.com/users/maflcko/repos",
      "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/maflcko/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 234877,
        "node_id": "MDU6TGFiZWwyMzQ4Nzc=",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Windows",
        "name": "Windows",
        "color": "884400",
        "default": false
      },
      {
        "id": 62963516,
        "node_id": "MDU6TGFiZWw2Mjk2MzUxNg==",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests",
        "name": "Tests",
        "color": "d4c5f9",
        "default": false
      },
      {
        "id": 5334691551,
        "node_id": "LA_kwDOABII588AAAABPfju3w",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/CI%20failed",
        "name": "CI failed",
        "description": "",
        "color": "cccccc",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "MEMBER",
    "locked": false,
    "comments": 3,
    "created_at": "2024-07-04T08:40:22Z",
    "updated_at": "2024-08-26T21:56:09Z"
  },
  "events": [
    {
      "event": "labeled",
      "id": 13391441572,
      "node_id": "LE_lADOABII586OeO6azwAAAAMeMS6k",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/13391441572",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-07-04T08:40:22Z",
      "label": {
        "name": "Windows",
        "color": "884400"
      }
    },
    {
      "event": "labeled",
      "id": 13391441582,
      "node_id": "LE_lADOABII586OeO6azwAAAAMeMS6u",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/13391441582",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-07-04T08:40:22Z",
      "label": {
        "name": "Tests",
        "color": "d4c5f9"
      }
    },
    {
      "event": "labeled",
      "id": 13391441587,
      "node_id": "LE_lADOABII586OeO6azwAAAAMeMS6z",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/13391441587",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-07-04T08:40:22Z",
      "label": {
        "name": "CI failed",
        "color": "cccccc"
      }
    },
    {
      "event": "commented",
      "id": 2208589062,
      "node_id": "IC_kwDOABII586DpGUG",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2208589062",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-07-04T09:59:39Z",
      "updated_at": "2024-07-04T09:59:39Z",
      "author_association": "MEMBER",
      "body": "Given that no one has reproduced this locally yet, this may be an issue limited to GHA.",
      "user": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2208589062",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2219919953,
      "node_id": "IC_kwDOABII586EUUpR",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2219919953",
      "actor": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-07-10T08:45:08Z",
      "updated_at": "2024-07-10T08:45:08Z",
      "author_association": "MEMBER",
      "body": "Seen recently here (`wallet_bumpfee.py --descriptors`) https://github.com/bitcoin/bitcoin/actions/runs/9863555844/job/27236587622#step:27:12496:\r\n```bash\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 188, in _raise_assertion_error\r\n                                       raise AssertionError(self._node_msg(msg))\r\n                                   AssertionError: [node 1] Unable to connect to bitcoind after 2400s\r\n test  2024-07-09T21:07:49.462000Z TestFramework (DEBUG): Closing down network thread \r\n```",
      "user": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2219919953",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2311170636,
      "node_id": "IC_kwDOABII586JwapM",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2311170636",
      "actor": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-08-26T21:56:08Z",
      "updated_at": "2024-08-26T21:56:08Z",
      "author_association": "CONTRIBUTOR",
      "body": "Would something like this be useful in helping approach the root cause of this?\r\n```diff\r\n--- a/test/functional/test_framework/test_node.py\r\n+++ b/test/functional/test_framework/test_node.py\r\n@@ -5,6 +5,7 @@\r\n \"\"\"Class for bitcoind node under test\"\"\"\r\n \r\n import contextlib\r\n+from collections import Counter\r\n import decimal\r\n import errno\r\n from enum import Enum\r\n@@ -260,6 +261,7 @@ class TestNode():\r\n         \"\"\"Sets up an RPC connection to the bitcoind process. Returns False if unable to connect.\"\"\"\r\n         # Poll at a rate of four times per second\r\n         poll_per_s = 4\r\n+        ignored_errors = Counter()\r\n         for _ in range(poll_per_s * self.rpc_timeout):\r\n             if self.process.poll() is not None:\r\n                 # Attach abrupt shutdown error/s to the exception message\r\n@@ -308,25 +310,31 @@ class TestNode():\r\n                 return\r\n             except JSONRPCException as e:  # Initialization phase\r\n                 # -28 RPC in warmup\r\n-                # -342 Service unavailable, RPC server started but is shutting down due to error\r\n-                if e.error['code'] != -28 and e.error['code'] != -342:\r\n+                if e.error['code'] == -28:\r\n+                    ignored_errors[\"-28 warmup\"] += 1\r\n+                else:\r\n                     raise  # unknown JSON RPC exception\r\n             except ConnectionResetError:\r\n                 # This might happen when the RPC server is in warmup, but shut down before the call to getblockcount\r\n                 # succeeds. Try again to properly raise the FailedToStartError\r\n+                ignored_errors[\"ConnectionResetError\"] += 1\r\n                 pass\r\n             except OSError as e:\r\n                 if e.errno == errno.ETIMEDOUT:\r\n+                    ignored_errors[\"OSError.ETIMEDOUT\"] += 1\r\n                     pass  # Treat identical to ConnectionResetError\r\n                 elif e.errno == errno.ECONNREFUSED:\r\n+                    ignored_errors[\"OSError.ETIMEDOUT\"] += 1\r\n                     pass  # Port not yet open?\r\n                 else:\r\n                     raise  # unknown OS error\r\n             except ValueError as e:  # cookie file not found and no rpcuser or rpcpassword; bitcoind is still starting\r\n-                if \"No RPC credentials\" not in str(e):\r\n+                if \"No RPC credentials\" in str(e):\r\n+                    ignored_errors[\"Waiting_for_credentials\"] += 1\r\n+                else:\r\n                     raise\r\n             time.sleep(1.0 / poll_per_s)\r\n-        self._raise_assertion_error(\"Unable to connect to bitcoind after {}s\".format(self.rpc_timeout))\r\n+        self._raise_assertion_error(\"Unable to connect to bitcoind after {}s (ignored_errors: {})\".format(self.rpc_timeout, str(dict(ignored_errors))))\r\n \r\n     def wait_for_cookie_credentials(self):\r\n         \"\"\"Ensures auth cookie credentials can be read, e.g. for testing CLI with -rpcwait before RPC connection is up.\"\"\"\r\n```\r\nNot sure if patches like this could be applied to some subset of CI to help debug CI-only issues, slightly unclean, but maybe you've done similar things before?\r\n\r\n**Notable**: I removed the case for \"-342 Service unavailable, RPC server started but is shutting down due to error\". Seems like we should be failing if the server is shutting down instead of *silently ignoring it*.",
      "user": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311170636",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    }
  ]
}