{
  "type": "issue",
  "issue": {
    "id": 2506029496,
    "node_id": "I_kwDOABII586VXvm4",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30818",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30818/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30818/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30818/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/30818",
    "number": 30818,
    "state": "open",
    "state_reason": null,
    "title": "Test Framework - test_framework.test_node.FailedToStartError: No RPC credentials",
    "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing issues\n\n### Current behaviour\n\n\r\nOn execution bitcoind fails to start and logs Failed to start error. Have pasted logs into the logs section. \r\n\r\nIt looks as though there is some rpc config required for this to run, but have not found a way to specify whats required. When i hard code a username/password in utils.py .. fails with Connection Refused. \r\n\r\n\r\n**Example Command**\r\n`\r\npython functional/feature_rbf.py --loglevel=DEBUG --tracerpc\r\n`\r\n\r\n**Config.ini**\r\n[environment]\r\nPACKAGE_NAME=Bitcoin Core\r\nPACKAGE_BUGREPORT=https://github.com/bitcoin/bitcoin/issues\r\nSRCDIR=/usr/src/bitcoin\r\nBUILDDIR=/usr/src/bitcoin\r\nEXEEXT=.exe\r\nRPCAUTH=/usr/src/bitcoin/share/rpcauth/rpcauth.py\r\n\r\n[components]\r\nENABLE_WALLET=true\r\nUSE_SQLITE=true\r\nUSE_BDB=true\r\nENABLE_CLI=true\r\nENABLE_BITCOIN_UTIL=true\r\nENABLE_WALLET_TOOL=true\r\nENABLE_BITCOIND=true\r\nENABLE_FUZZ_BINARY=true\r\nENABLE_ZMQ=true\r\n#ENABLE_EXTERNAL_SIGNER=true\r\n#ENABLE_USDT_TRACEPOINTS=true\r\n`\r\n\r\n**Bitcoin.conf (autogenerated)**\r\n`\r\n\r\nregtest=1\r\n[regtest]\r\nport=12201\r\nrpcport=17201\r\nrpcservertimeout=99000\r\nrpcdoccheck=1\r\nfallbackfee=0.0002\r\nserver=1\r\nkeypool=1\r\ndiscover=0\r\ndnsseed=0\r\nfixedseeds=0\r\nlistenonion=0\r\npeertimeout=999999999\r\nprinttoconsole=0\r\nupnp=0\r\nnatpmp=0\r\nshrinkdebugfile=0\r\ndeprecatedrpc=create_bdb\r\nunsafesqlitesync=1\r\nconnect=0\r\nbind=127.0.0.1\r\n`\r\n\r\n\n\n### Expected behaviour\n\nThe test should run to completion. \n\n### Steps to reproduce\n\nBuild 27.* on Ubuntu WLS\r\n\r\nExecute python test with example command. \r\npython functional/feature_rbf.py --loglevel=DEBUG --tracerpc\n\n### Relevant log output\n\n`\r\n2024-09-04T18:07:10.779000Z TestFramework (INFO): PRNG seed is: 4851958720779390906\r\n2024-09-04T18:07:10.779000Z TestFramework (DEBUG): Setting up network thread\r\n2024-09-04T18:07:10.780000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_u9zpt_2g\r\n2024-09-04T18:07:10.780000Z TestFramework (DEBUG): Copy cache directory /usr/src/bitcoin/test/cache/node0 to node 0\r\n2024-09-04T18:07:10.781000Z TestFramework (DEBUG): Copy cache directory /usr/src/bitcoin/test/cache/node0 to node 1\r\n2024-09-04T18:07:10.783000Z TestFramework.node0 (DEBUG): ['/usr/src/bitcoin/src/bitcoind.exe', '-datadir=/tmp/bitcoin_func_test_u9zpt_2g/node0', '-logtimemicros', '-debug', '-debugexclude=libevent', '-debugexclude=leveldb', '-debugexclude=rand', '-uacomment=testnode0', '-logthreadnames', '-logsourcelocations', '-loglevel=trace', '-v2transport=0']\r\n2024-09-04T18:07:10.783000Z TestFramework.node0 (DEBUG): ['-maxorphantx=1000', '-limitancestorcount=50', '-limitancestorsize=101', '-limitdescendantcount=200', '-limitdescendantsize=101']\r\n2024-09-04T18:07:10.783000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-09-04T18:07:10.784000Z TestFramework.node1 (DEBUG): ['/usr/src/bitcoin/src/bitcoind.exe', '-datadir=/tmp/bitcoin_func_test_u9zpt_2g/node1', '-logtimemicros', '-debug', '-debugexclude=libevent', '-debugexclude=leveldb', '-debugexclude=rand', '-uacomment=testnode1', '-logthreadnames', '-logsourcelocations', '-loglevel=trace', '-v2transport=0']\r\n2024-09-04T18:07:10.784000Z TestFramework.node1 (DEBUG): []\r\n2024-09-04T18:07:10.784000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up\r\n2024-09-04T18:07:10.784000Z TestFramework.utils (DEBUG): /tmp/bitcoin_func_test_u9zpt_2g/node0/bitcoin.conf\r\n2024-09-04T18:07:10.784000Z TestFramework.node0 (DEBUG): Value Error No RPC credentials\r\n....\r\n2024-09-04T18:07:14.552000Z TestFramework.utils (DEBUG): /tmp/bitcoin_func_test_u9zpt_2g/node0/bitcoin.conf\r\n2024-09-04T18:07:14.552000Z TestFramework.node0 (DEBUG): Value Error No RPC credentials\r\n2024-09-04T18:07:14.803000Z TestFramework.node0 (DEBUG): Stopping node\r\n2024-09-04T18:07:14.804000Z TestFramework (ERROR): Assertion failed\r\nTraceback (most recent call last):\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 556, in start_nodes\r\n    node.wait_for_rpc_connection()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_node.py\", line 260, in wait_for_rpc_connection\r\n    raise FailedToStartError(self._node_msg(\r\n**test_framework.test_node.FailedToStartError: [node 0] bitcoind exited with status 1 during initialization. Error: Specified data directory \"/tmp/bitcoin_func_test_u9zpt_2g/node0\" does not exist.**\r\n************************\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 130, in main     self.setup()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 297, in setup     self.setup_network()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 391, in setup_network     self.setup_nodes()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 413, in setup_nodes     self.start_nodes()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 559, in start_nodes     self.stop_nodes()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 574, in stop_nodes     node.stop_node(wait=wait, wait_until_stopped=False)\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_node.py\", line 386, in stop_node     self.stop(wait=wait)\r\n  **File \"/usr/src/bitcoin/test/functional/test_framework/test_node.py\", line 207, in __getattr__    assert self.rpc_connected and self.rpc is not None, self._node_msg(\"Error: no RPC connection\") AssertionError: [node 0] Error: no RPC connection**\r\n\r\n2024-09-04T18:07:14.806000Z TestFramework (DEBUG): Closing down network thread\r\n2024-09-04T18:07:14.857000Z TestFramework (INFO): Stopping nodes\r\n2024-09-04T18:07:14.857000Z TestFramework.node0 (DEBUG): Stopping node\r\nTraceback (most recent call last):\r\n  File \"/usr/src/bitcoin/test/functional/feature_rbf.py\", line 731, in <module>\r\n    ReplaceByFeeTest().main()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 154, in main\r\n    exit_code = self.shutdown()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 313, in shutdown\r\n    self.stop_nodes()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 574, in stop_nodes\r\n    node.stop_node(wait=wait, wait_until_stopped=False)\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_node.py\", line 386, in stop_node\r\n    self.stop(wait=wait)\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_node.py\", line 207, in __getattr__\r\n    assert self.rpc_connected and self.rpc is not None, self._node_msg(\"Error: no RPC connection\")\r\n\r\nAssertionError: [node 0] Error: no RPC connection\r\n\r\n[node 1] Cleaning up leftover process\r\n[node 0] Cleaning up leftover process\r\n`\n\n### How did you obtain Bitcoin Core\n\nCompiled from source\n\n### What version of Bitcoin Core are you using?\n\nv27.1.0\n\n### Operating system and version\n\nUbuntu 22.04.4 LTS\n\n### Machine specifications\n\nWindows 11 Home\r\n8 Core i7 9700\r\n32 GB Ram\r\n",
    "user": {
      "login": "somethingbeta",
      "id": 6619766,
      "node_id": "MDQ6VXNlcjY2MTk3NjY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6619766?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/somethingbeta",
      "html_url": "https://github.com/somethingbeta",
      "followers_url": "https://api.github.com/users/somethingbeta/followers",
      "following_url": "https://api.github.com/users/somethingbeta/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/somethingbeta/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/somethingbeta/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/somethingbeta/subscriptions",
      "organizations_url": "https://api.github.com/users/somethingbeta/orgs",
      "repos_url": "https://api.github.com/users/somethingbeta/repos",
      "events_url": "https://api.github.com/users/somethingbeta/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/somethingbeta/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [],
    "assignees": [],
    "author_association": "NONE",
    "locked": false,
    "comments": 0,
    "created_at": "2024-09-04T18:31:38Z",
    "updated_at": "2024-09-04T18:31:38Z"
  },
  "events": []
}